### ISSUE TITLE
Execute conditional lint execution in `travis.yml` when on `master` branch

### ISSUE THREAD

**Issue by sven1103** [SciLifeLab/NGI-NFcookiecutter#16]
Motivated by the enhancement of nf-core lint https://github.com/nf-core/tools/pull/24.

Adapt the `.travis.yml` template such that git activity on the master branch executes nf-core lint with the `--release` flag for production-ready workflows.

- [ ] Conditionally execute lint tests with `--release` flag, when git activity happens on the master branch (check env var TRAVIS_BRANCH)

**Comment by ewels** [comment]
Maybe we can get the `tools` package to recognise the relevant travis env variables and set `--release` automatically, so that the travis config files don’t have to have this logic? Would only be a few extra characters in the tools package and avoids extra complexity across all travis configs.. Having the command line flag still means that people can test easily locally..

**Comment by sven1103** [comment]
Ah I see, yes this is also fine for me. Good point :)

**Comment by ewels** [comment]
I realise that this is the complete opposite thing that I [said yesterday](https://github.com/nf-core/tools/issues/23#issuecomment-374607783) by the way. 🤦‍♂️  Sorry.. But this way we can have our cake and eat it - automated and easy manual testing 😁

**Comment by sven1103** [comment]
Ah everything is fine :)
